### PR TITLE
Update README.MD

### PR DESCRIPTION
**Pull request by xshram**
Rebuilded for Fedora [29,30,Rawhide]

### CODE REVIEW

**Comment by naelstrof** [comment]
You've deleted all of the readme, I can't pull this as it is.

**Comment by xshram** [comment]
I am so sorry about. I just wanted to replace link to new copr (fedora)
I rebuilded for f30. New link

https://copr.fedorainfracloud.org/coprs/xshramx/maim/

**Comment by naelstrof** [comment]
If you want to make a new pull request with the updated link, I'll merge it for you!
You can also fix this one up to have the original README.md.

**Comment by xshram** [comment]
I have updated README with my link. 
Sorry for any inconvenience, i am just newbie.

**Comment by naelstrof** [comment]
Do you mind doing a fresh pull request with just one commit? Or do an interactive rebase to clean up your commits before I merge?

Try avoid testing on the main branch.

**Pull request closed without merging**
